---

- name: Install apache2 and php
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: 
      - apache2
      - apache2-utils
      - php
      - libapache2-mod-php
      - php-mysql