---
- name: Create webroot
  file:
    state: directory
    path: /var/www/html/
    owner: root
    group: root
    mode: 0755

- name: Download WordPress
  get_url: 
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz 

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz 
    dest: /tmp
    owner: www-data
    group: www-data
    copy: no

- name: Check index.html
  stat:
    path: /var/www/html/index.html
  register: indexHtml_result

- name: Move index.html 
  command: mv /var/www/html/index.html /tmp/
  when: indexHtml_result.stat.exists == True

- name: Check index.php
  stat:
    path: /var/www/html/index.php
  register: indexPhp_result

- name: Move WordPress install files
  shell: mv /tmp/wordpress/* /var/www/html/
  when: indexPhp_result.stat.exists == False

- name: Check wp-config.php
  stat:
    path: /var/www/html/wp-config.php
  register: configPhp_result

- name: Configure wordPress
  template:
    src: wp-config.php
    dest: /var/www/html/
  when: configPhp_result.stat.exists == False

- name: Remove WordPress folder
  shell: rm -rf /tmp/wordpress


